services:
  - type: web
    name: microgrid-mvp
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
